version: '3.3'
services:
  db-desafio_1:
    image: mysql:5.7
    container_name: 'db_desafio'
    restart: always
    environment:
      MYSQL_DATABASE: 'xxx_db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'p455w0rd'
      MYSQL_ROOT_PASSWORD: 'p455w0rd'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db-desafio_1:/var/lib/mysql
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq


volumes:
  my-db-desafio_1: